<!--
This file will be copied in ./terraform-provider/list-resources/index.md
The reason is that we need to add this file to a folder to make RTD aware of the subfolder
after it has been generated by github.com/hashicorp/terraform-plugin-docs/cmd/tfplugindocs.
-->

# List resources

```{toctree}
:titlesonly:
:glob:

*

```
