// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/juju/terraform-provider-juju/internal/provider (interfaces: JujuCommand)
//
// Generated by this command:
//
//	mockgen -typed -package provider -destination mock_test.go github.com/juju/terraform-provider-juju/internal/provider JujuCommand
//

// Package provider is a generated GoMock package.
package provider

import (
	context "context"
	reflect "reflect"

	juju "github.com/juju/terraform-provider-juju/internal/juju"
	gomock "go.uber.org/mock/gomock"
)

// MockJujuCommand is a mock of JujuCommand interface.
type MockJujuCommand struct {
	ctrl     *gomock.Controller
	recorder *MockJujuCommandMockRecorder
	isgomock struct{}
}

// MockJujuCommandMockRecorder is the mock recorder for MockJujuCommand.
type MockJujuCommandMockRecorder struct {
	mock *MockJujuCommand
}

// NewMockJujuCommand creates a new mock instance.
func NewMockJujuCommand(ctrl *gomock.Controller) *MockJujuCommand {
	mock := &MockJujuCommand{ctrl: ctrl}
	mock.recorder = &MockJujuCommandMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJujuCommand) EXPECT() *MockJujuCommandMockRecorder {
	return m.recorder
}

// Bootstrap mocks base method.
func (m *MockJujuCommand) Bootstrap(ctx context.Context, model juju.BootstrapArguments) (*juju.ControllerConnectionInformation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Bootstrap", ctx, model)
	ret0, _ := ret[0].(*juju.ControllerConnectionInformation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Bootstrap indicates an expected call of Bootstrap.
func (mr *MockJujuCommandMockRecorder) Bootstrap(ctx, model any) *MockJujuCommandBootstrapCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Bootstrap", reflect.TypeOf((*MockJujuCommand)(nil).Bootstrap), ctx, model)
	return &MockJujuCommandBootstrapCall{Call: call}
}

// MockJujuCommandBootstrapCall wrap *gomock.Call
type MockJujuCommandBootstrapCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockJujuCommandBootstrapCall) Return(arg0 *juju.ControllerConnectionInformation, arg1 error) *MockJujuCommandBootstrapCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockJujuCommandBootstrapCall) Do(f func(context.Context, juju.BootstrapArguments) (*juju.ControllerConnectionInformation, error)) *MockJujuCommandBootstrapCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockJujuCommandBootstrapCall) DoAndReturn(f func(context.Context, juju.BootstrapArguments) (*juju.ControllerConnectionInformation, error)) *MockJujuCommandBootstrapCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Config mocks base method.
func (m *MockJujuCommand) Config(ctx context.Context, connInfo *juju.ControllerConnectionInformation) (map[string]any, map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Config", ctx, connInfo)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(map[string]any)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Config indicates an expected call of Config.
func (mr *MockJujuCommandMockRecorder) Config(ctx, connInfo any) *MockJujuCommandConfigCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Config", reflect.TypeOf((*MockJujuCommand)(nil).Config), ctx, connInfo)
	return &MockJujuCommandConfigCall{Call: call}
}

// MockJujuCommandConfigCall wrap *gomock.Call
type MockJujuCommandConfigCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockJujuCommandConfigCall) Return(arg0, arg1 map[string]any, arg2 error) *MockJujuCommandConfigCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockJujuCommandConfigCall) Do(f func(context.Context, *juju.ControllerConnectionInformation) (map[string]any, map[string]any, error)) *MockJujuCommandConfigCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockJujuCommandConfigCall) DoAndReturn(f func(context.Context, *juju.ControllerConnectionInformation) (map[string]any, map[string]any, error)) *MockJujuCommandConfigCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Destroy mocks base method.
func (m *MockJujuCommand) Destroy(ctx context.Context, args juju.DestroyArguments) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Destroy", ctx, args)
	ret0, _ := ret[0].(error)
	return ret0
}

// Destroy indicates an expected call of Destroy.
func (mr *MockJujuCommandMockRecorder) Destroy(ctx, args any) *MockJujuCommandDestroyCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Destroy", reflect.TypeOf((*MockJujuCommand)(nil).Destroy), ctx, args)
	return &MockJujuCommandDestroyCall{Call: call}
}

// MockJujuCommandDestroyCall wrap *gomock.Call
type MockJujuCommandDestroyCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockJujuCommandDestroyCall) Return(arg0 error) *MockJujuCommandDestroyCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockJujuCommandDestroyCall) Do(f func(context.Context, juju.DestroyArguments) error) *MockJujuCommandDestroyCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockJujuCommandDestroyCall) DoAndReturn(f func(context.Context, juju.DestroyArguments) error) *MockJujuCommandDestroyCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateConfig mocks base method.
func (m *MockJujuCommand) UpdateConfig(ctx context.Context, connInfo *juju.ControllerConnectionInformation, controllerConfig, controllerModelConfig map[string]string, unsetControllerModelConfig []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateConfig", ctx, connInfo, controllerConfig, controllerModelConfig, unsetControllerModelConfig)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateConfig indicates an expected call of UpdateConfig.
func (mr *MockJujuCommandMockRecorder) UpdateConfig(ctx, connInfo, controllerConfig, controllerModelConfig, unsetControllerModelConfig any) *MockJujuCommandUpdateConfigCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateConfig", reflect.TypeOf((*MockJujuCommand)(nil).UpdateConfig), ctx, connInfo, controllerConfig, controllerModelConfig, unsetControllerModelConfig)
	return &MockJujuCommandUpdateConfigCall{Call: call}
}

// MockJujuCommandUpdateConfigCall wrap *gomock.Call
type MockJujuCommandUpdateConfigCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockJujuCommandUpdateConfigCall) Return(arg0 error) *MockJujuCommandUpdateConfigCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockJujuCommandUpdateConfigCall) Do(f func(context.Context, *juju.ControllerConnectionInformation, map[string]string, map[string]string, []string) error) *MockJujuCommandUpdateConfigCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockJujuCommandUpdateConfigCall) DoAndReturn(f func(context.Context, *juju.ControllerConnectionInformation, map[string]string, map[string]string, []string) error) *MockJujuCommandUpdateConfigCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
