// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/juju/terraform-provider-juju/internal/provider (interfaces: jujuCommand)
//
// Generated by this command:
//
//	mockgen -typed -package provider -destination mock_test.go github.com/juju/terraform-provider-juju/internal/provider jujuCommand
//

// Package provider is a generated GoMock package.
package provider

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockjujuCommand is a mock of jujuCommand interface.
type MockjujuCommand struct {
	ctrl     *gomock.Controller
	recorder *MockjujuCommandMockRecorder
	isgomock struct{}
}

// MockjujuCommandMockRecorder is the mock recorder for MockjujuCommand.
type MockjujuCommandMockRecorder struct {
	mock *MockjujuCommand
}

// NewMockjujuCommand creates a new mock instance.
func NewMockjujuCommand(ctrl *gomock.Controller) *MockjujuCommand {
	mock := &MockjujuCommand{ctrl: ctrl}
	mock.recorder = &MockjujuCommandMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockjujuCommand) EXPECT() *MockjujuCommandMockRecorder {
	return m.recorder
}

// Bootstrap mocks base method.
func (m *MockjujuCommand) Bootstrap(ctx context.Context, model boostrapArguments) (*controllerConnectionInformation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Bootstrap", ctx, model)
	ret0, _ := ret[0].(*controllerConnectionInformation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Bootstrap indicates an expected call of Bootstrap.
func (mr *MockjujuCommandMockRecorder) Bootstrap(ctx, model any) *MockjujuCommandBootstrapCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Bootstrap", reflect.TypeOf((*MockjujuCommand)(nil).Bootstrap), ctx, model)
	return &MockjujuCommandBootstrapCall{Call: call}
}

// MockjujuCommandBootstrapCall wrap *gomock.Call
type MockjujuCommandBootstrapCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockjujuCommandBootstrapCall) Return(arg0 *controllerConnectionInformation, arg1 error) *MockjujuCommandBootstrapCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockjujuCommandBootstrapCall) Do(f func(context.Context, boostrapArguments) (*controllerConnectionInformation, error)) *MockjujuCommandBootstrapCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockjujuCommandBootstrapCall) DoAndReturn(f func(context.Context, boostrapArguments) (*controllerConnectionInformation, error)) *MockjujuCommandBootstrapCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Config mocks base method.
func (m *MockjujuCommand) Config(ctx context.Context, connInfo *controllerConnectionInformation) (map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Config", ctx, connInfo)
	ret0, _ := ret[0].(map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Config indicates an expected call of Config.
func (mr *MockjujuCommandMockRecorder) Config(ctx, connInfo any) *MockjujuCommandConfigCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Config", reflect.TypeOf((*MockjujuCommand)(nil).Config), ctx, connInfo)
	return &MockjujuCommandConfigCall{Call: call}
}

// MockjujuCommandConfigCall wrap *gomock.Call
type MockjujuCommandConfigCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockjujuCommandConfigCall) Return(arg0 map[string]string, arg1 error) *MockjujuCommandConfigCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockjujuCommandConfigCall) Do(f func(context.Context, *controllerConnectionInformation) (map[string]string, error)) *MockjujuCommandConfigCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockjujuCommandConfigCall) DoAndReturn(f func(context.Context, *controllerConnectionInformation) (map[string]string, error)) *MockjujuCommandConfigCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Destroy mocks base method.
func (m *MockjujuCommand) Destroy(ctx context.Context, connInfo *controllerConnectionInformation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Destroy", ctx, connInfo)
	ret0, _ := ret[0].(error)
	return ret0
}

// Destroy indicates an expected call of Destroy.
func (mr *MockjujuCommandMockRecorder) Destroy(ctx, connInfo any) *MockjujuCommandDestroyCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Destroy", reflect.TypeOf((*MockjujuCommand)(nil).Destroy), ctx, connInfo)
	return &MockjujuCommandDestroyCall{Call: call}
}

// MockjujuCommandDestroyCall wrap *gomock.Call
type MockjujuCommandDestroyCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockjujuCommandDestroyCall) Return(arg0 error) *MockjujuCommandDestroyCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockjujuCommandDestroyCall) Do(f func(context.Context, *controllerConnectionInformation) error) *MockjujuCommandDestroyCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockjujuCommandDestroyCall) DoAndReturn(f func(context.Context, *controllerConnectionInformation) error) *MockjujuCommandDestroyCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateConfig mocks base method.
func (m *MockjujuCommand) UpdateConfig(ctx context.Context, connInfo *controllerConnectionInformation, config map[string]string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateConfig", ctx, connInfo, config)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateConfig indicates an expected call of UpdateConfig.
func (mr *MockjujuCommandMockRecorder) UpdateConfig(ctx, connInfo, config any) *MockjujuCommandUpdateConfigCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateConfig", reflect.TypeOf((*MockjujuCommand)(nil).UpdateConfig), ctx, connInfo, config)
	return &MockjujuCommandUpdateConfigCall{Call: call}
}

// MockjujuCommandUpdateConfigCall wrap *gomock.Call
type MockjujuCommandUpdateConfigCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockjujuCommandUpdateConfigCall) Return(arg0 error) *MockjujuCommandUpdateConfigCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockjujuCommandUpdateConfigCall) Do(f func(context.Context, *controllerConnectionInformation, map[string]string) error) *MockjujuCommandUpdateConfigCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockjujuCommandUpdateConfigCall) DoAndReturn(f func(context.Context, *controllerConnectionInformation, map[string]string) error) *MockjujuCommandUpdateConfigCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
