name: Periodic Style Checks

on:
  schedule:
    - cron: "0 1 * * 4" # Runs at 01:00 AM on every Wednesday

jobs:
  vale:
    name: Style checker
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash
        working-directory: "docs-rtd"
    steps:
      - uses: actions/checkout@v5
      - name: Run vale
        run: |
          make vale
